name: Clear deployments on closed Pull Requests

on:
  pull_request:
    branches:
      - master
    types: [closed]

jobs:
  clear:
    runs-on: ubuntu-latest
    env:
      ACTIONS_PULL_REQUEST_HEAD: ${{ github.event.pull_request.head.sha }}
      ACTIONS_PULL_REQUEST_NUMBER: ${{ github.event.number }}
      GITHUB_TOKEN: ${{ github.token }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Clear deployments
      run: ./config/gh-actions/delete.sh
